image: gitpod/workspace-full:latest

tasks:
  - init: |
      # 安装 PHP 依赖
      composer install --prefer-dist
      # 复制环境变量文件（确保你仓库中有 .env.example 文件）
      cp .env.example .env
      # 生成 Laravel 应用密钥
      php artisan key:generate
  - command: |
      # 启动 Laravel 开发服务器
      php artisan serve --host=0.0.0.0 --port=8000

ports:
  - port: 8000
    onOpen: open-preview
